# Run tests across every micra module.
test:
    cd core && go test ./...
    cd adapters/loggerslog && go test ./...
    cd adapters/otelinit && go test ./...
    cd adapters/otelpgx && go test ./...
    cd components/pgxpool && go test ./...
    cd components/httpserver && go test ./...
    cd components/grpcserver && go test ./...
    cd components/grpcclient && go test ./...

# Run vet across every micra module.
vet:
    cd core && go vet ./...
    cd adapters/loggerslog && go vet ./...
    cd adapters/otelinit && go vet ./...
    cd adapters/otelpgx && go vet ./...
    cd components/pgxpool && go vet ./...
    cd components/httpserver && go vet ./...
    cd components/grpcserver && go vet ./...
    cd components/grpcclient && go vet ./...

# Tidy every module's go.mod.
tidy:
    cd core && go mod tidy
    cd adapters/loggerslog && go mod tidy
    cd adapters/otelinit && go mod tidy
    cd adapters/otelpgx && go mod tidy
    cd components/pgxpool && go mod tidy
    cd components/httpserver && go mod tidy
    cd components/grpcserver && go mod tidy
    cd components/grpcclient && go mod tidy
